/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

 var sayings = [
 	"Get ready to rumble!",
	"Welcome to Club Med",
	"Beach Body in Progress",
	"Work those abs",
	"I'm sexy and I know it!"
 ];
 
//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//
$(function() {

		
	/*$('#speed-startstop').click(function(e) {
		console.log($(this).text());
		if($(this).text() == "RUN")		
			treadmill.setSpeed("2.2");
		else
			treadmill.setSpeed("STOP");
		});*/
		
		$("#enter-weight").TouchSpin({
			width: '150px',
			min: 50, // Minimum value.
			max: 600, // Maximum value.
			boostat: 5, // Boost at every nth step.
			maxboostedstep: 10, // Maximum step when boosted.
			postfix: 'lbs', // Text after the input.
			step: 1, // Incremental/decremental step on up/down change.
			stepinterval: 100, // Refresh rate of the spinner in milliseconds.
			stepintervaldelay: 500 // Time in milliseconds before the spinner starts to spin.
			});

	var form = $("#user-select-form");
	$("#user-select").on("show.bs.modal", function() { 
		//$("#user-select.modal .modal-title").text(sayings[Math.floor(Math.random()*sayings.length)]);
		$("#user-select.modal .modal-footer .qotd").html(qotd_rich());
	});

	$("#session-start").on("click", function() {
		var user = form.find("input:radio[name=user]:checked").val();
		var weight = form.find("input[name=weight]").val();
		console.log("session[user:"+user+", weight:"+weight+"]");
		treadmill.setUser(user, LbsToKg(weight));
	});
	
	// show some debug info
	var s = "<hr/>width:"+window.innerWidth+"  height:"+window.innerHeight;
	$("div#debug").html(s);

	// pop the dialog to select which user will run
	//$("#user-select").modal();
});


Treadmill.prototype.onSpeedChanged = function(value) 
{
	if(value==0.0)
		$(".speed-indicator").text("0");
    else
    	$(".speed-indicator").text(value.toFixed(1));   
	if(this.dial)
	{
		this.dial.setSpeed(value);
	}
}

Treadmill.prototype.onInclineChanged = function(value)
{
    //$("#InclineIndicator").text(Math.round(value));
}

Treadmill.prototype.onUpdateRunningTime = function(seconds, minutes, hours)
{
    var rt = zeropad(minutes)+":"+zeropad(seconds);
    if(hours>0)	// more than an hour
		rt = hours+":"+rt;
	$(".running-time").text(rt);
	if(this.dial) this.dial.setRunningTime(seconds,minutes,hours);
}

function SetFavSpeed(event)
{
    treadmill.setSpeed($(event.target).text());
}



function decline(event)
{
    treadmill.inclineDown();
}


function incline(event)
{
    treadmill.inclineUp();
}


function inclineFloor(event)
{
    treadmill.floor();
}

function KgToLbs(kg)
{
	return Math.round(kg*2.2);
}


function LbsToKg(lbs)
{
	return lbs/2.2;
}
