/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

var prefKey = "treadstation-ip";
var treadmill = null;

//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//
$(function() {
    treadmill = new Treadmill();
	
	$('#startstop').click(function() {
		treadmill.setSpeed("2.6");
	});
	
	$('#slower').on('click', function() {
		treadmill.decreaseSpeed();
	});

	$('#faster').on('click', function() {
		treadmill.increaseSpeed();
	});
	
    treadmill.connect("192.168.2.48");
});


Treadmill.prototype.onSpeedChanged = function(value) 
{
    $("#SpeedIndicator").text(value.toFixed(1));    
}

Treadmill.prototype.onInclineChanged = function(value)
{
    $("#InclineIndicator").text(Math.round(value));
}

Treadmill.prototype.onUpdateRunningTime = function(seconds, minutes, hours)
{
	return false;
    $("#RunningSeconds").text( zeropad(seconds) );
    $("#RunningMinutes").text( zeropad(minutes) );
    if(hours>0)	// more than an hour
    {
        $("#RunningHours").text( hours );
    } else {
        $("#RunningHours").text( "" );
    }
}

function SetFavSpeed(event)
{
    treadmill.setSpeed($(event.target).text());
}



function decline(event)
{
    treadmill.inclineDown();
}


function incline(event)
{
    treadmill.inclineUp();
}


function inclineFloor(event)
{
    treadmill.floor();
}

